line-length = 120
target-version = "py312"

[lint]
ignore = [
  "E501",
  "ANN401",
  "ANN101",
  "ANN102",
  "PLR0913",
  "PLR2004",
  "PLR0917",
  "PLR6301",
  "ANN002",
  "ERA001",
  "RUF006",
  "D",
  "CPY",
  "DOC",
  "TID",
  "INP",
  "S101",
  "SLF001",
  "FBT",
  "COM812",
  "ISC001",
  "S311",
  "BLE001",
  "PLR0912",
  "PLR0915",
  "C901",
  "PLR0911",
  "PLR0916",
  "PLR0904",
  "PLR0914",
  "PLR0904",
  "FIX",
  "TD",
  "S105",
  "S301",
  "RUF012",
  "S403",
]
preview = true
select = [
  "ALL",
]

[lint.per-file-ignores]
"**/__init__.py" = ["F403", "F401"]
"./migrations/*.py" = ["ALL"]
"hoyo_buddy/draw/**/*.py" = ["PLR", "C"]
"hoyo_buddy/draw/drawer.py" = ["F405"]
"hoyo_buddy/models.py" = ["TCH002"]
"playground.*.py" = ["ALL"]

[lint.flake8-type-checking]
quote-annotations = true
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

[lint.mccabe]
max-complexity = 15

[lint.pydocstyle]
convention = "google"

[lint.isort]
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
