name: Ruff lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'hoyo_buddy/**.py'
      - 'run.py'
      - 'run_web_app.py'
      - '.github/workflows/ruff-lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'hoyo_buddy/**.py'
      - 'run.py'
      - 'run_web_app.py'
      - '.github/workflows/ruff-lint.yml'

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3